### ISSUE TITLE
axis collapse to zero on complex_plot

### ISSUE THREAD

**Issue by ilijanikolov** [vemiBGH/PULSEE#62]
![63fc4328-1975-4101-8191-feb863c3be73](https://github.com/vemiBGH/PULSEE/assets/28354586/bf3c620c-df9d-496f-ab29-83c977f8ffaa)

**Comment by jiwooseo98** [comment]
Fixed with commit: 7e96f0e9b287b9ea1ce4e96bf4f71f27f8a3eda0

Will keep an eye on it in the future to see if plots behave differently, since `constrained_layout` has been turned off
